//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int Userr { get; set; }
        public int CV { get; set; }
        public int Companyy { get; set; }
        public int Postingg { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CV CV1 { get; set; }
        public virtual Posting Posting { get; set; }
        public virtual User User { get; set; }
    }
}
